services:
  postgresql:
    image: 'postgres'
    restart: always
    container_name: 'backend-db'
    hostname: localhost
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${DATABASE_USER} -d ${DATABASE_NAME} -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      # - ./pgdata:/var/lib/postgresql/data
      # uncomment above to persist data
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgresql:
        condition: service_healthy